# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89aa2cdfe556d7a8e3f30bfa2c01a82e34bdbdf222401a50064b275f162afc97f12d79b1d0fb54812f585fd6ad7f51c4433d63a6e2f654dbb6e6436ccefb8390

test:
  secret_key_base: 780c47e994e89b08dbecdc7c775bd8aab241490164f0e59ec12296fc2eff605c300b2210e3d021f41c84a3ee56f65f674d1eab129c29d794c797cf7f536b7965

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
